# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Run Bazel Tests
on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_call:
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Cache Bazel and pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/bazel
            ~/.cache/pip
          key: ${{ runner.os }}-test-${{ hashFiles('**/*.bazel', '**/BUILD', '**/*.bzl', 'src/requirements.txt', 'src/**/*.py') }}

      - name: Setup Bazel with cache
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          disk-cache: true
          repository-cache: true
          bazelisk-cache: true
      - name: Run test targets
        run: |
          bazel run //:ide_support
          bazel test //src/...

      - name: Prepare bundled consumer report
        if: always()
        # Creating tests-report directory
        # Follow Symlinks via '-L' to copy correctly
        # Copy everything inside the 'test-reports' folder
        run: |
          mkdir -p tests-report
          rsync -amL --include='*/' --include='test.xml' --include='test.log' --exclude='*' bazel-testlogs/ tests-report/

      - name: Upload bundled consumer report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tests-report
          path: tests-report
